drop if exists products;

create table products {
(
    id bigint generated by default as identity,
    description varchar(255),
    name VARCHAR(64) not null,
    price decimal(19,2),
    quantity integer,
    category_id bigint,
    primary key (id)
 );