drop table if exists public.products CASCADE;

create table products
(
    id          bigint generated by default as identity,
    description varchar(256),
    name        VARCHAR(64) not null,
    price       decimal(19, 2),
    quantity    integer,
    category_id bigint,
    primary key (id)
);

drop table if exists public.category CASCADE;

create table category
(
    id          bigint generated by default as identity,
    description VARCHAR(256) not null,
    name        VARCHAR(32)  not null,
    parent_id   bigint,
    primary key (id)
);