drop table if exists public.orders CASCADE;

create table orders
(
    id bigint generated by default as identity,
    total_price double precision not null,
    user_id  bigint not null,
    status VARCHAR(32) not null,
    CREATE_DATE timestamp   not null,
    modify_date timestamp   not null,
    primary key (id)
);

drop table if exists public.users CASCADE;

create table users
(
    id          bigint generated by default as identity,
    active      VARCHAR(16) not null,
    created_at  timestamp   not null,
    email       VARCHAR(32) not null,
    first_name  VARCHAR(32) not null,
    last_name   VARCHAR(32) not null,
    login       VARCHAR(32) not null,
    password    VARCHAR(16) not null,
    phone       VARCHAR(16) not null,
    updated_at  timestamp,
    is_verified VARCHAR(16) not null,
    primary key (id)
);