drop table if exists public.users CASCADE;

create table users
(
    id          bigint generated by default as identity,
    active      VARCHAR(16),
    created_at  timestamp,
    email       VARCHAR(32),
    first_name  VARCHAR(32),
    last_name   VARCHAR(32),
    login       VARCHAR(32),
    password    VARCHAR(16),
    phone       VARCHAR(16),
    updated_at  timestamp,
    is_verified VARCHAR(16),
    primary key (id)
);